### ISSUE TITLE
Al modificar el perfil aparece una excepción

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#6]
```
  StandardWrapperValve[EditarPerfilServlet]: Servlet.service() for servlet EditarPerfilServlet threw exception
java.lang.IllegalStateException
	at org.apache.catalina.connector.ResponseFacade.sendRedirect(ResponseFacade.java:518)
	at servlets.EditarPerfilServlet.processRequest(EditarPerfilServlet.java:97)
	at servlets.EditarPerfilServlet.doPost(EditarPerfilServlet.java:126)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
       ...
```

Creo que es porque se hacen dos redirecciones a la vez y peta.

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ANTES DE AÑADIR NUEVOS TRABAJOS, CORREGID LO QUE ESTÁ HECHO](https://trello.com/c/vK3CtVqh/38-antes-de-anadir-nuevos-trabajos-corregid-lo-que-esta-hecho)

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ANTES DE AÑADIR NUEVOS TRABAJOS, CORREGID LO QUE ESTÁ HECHO](https://trello.com/c/vK3CtVqh/38-antes-de-anadir-nuevos-trabajos-corregid-lo-que-esta-hecho)
